### ISSUE TITLE
Support for ETegro Hyperion RS230 G4 Backplane 

### ISSUE THREAD

**Issue by astor2-team** [ETegro/OpenSAN#1]
Add ability for render front panel of Hyperion RS230 G4 in "SAN->Monitoring" tab.

**Comment by Difrex** [comment]
On 10.04.2013 16:36, OpenSAN Development Team wrote:

> Add ability for render front panel of Hyperion RS230 G4 in 
> "SAN->Monitoring" tab.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/astor2-team/astor2/issues/1.
> 
> Work in progress.

/This is test reply from email./
